=== niclasdumesnil/marvelsdb_fanmade_data/schema/card_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"additionalProperties": true,
	"dependencies": {
		"name": [
			"faction_code",
			"type_code"
		]
	},
	"description": "JSON Schema for a Marvel Champions card — derived from Card.orm.yml",
	"properties": {
		"alt_art": {
			"type": "boolean"
		},
		"attack": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"attack_cost": {
			"minimum": 0,
			"type": "integer"
		},
		"attack_star": {
			"type": "boolean"
		},
		"back_flavor": {
			"minLength": 1,
			"type": "string"
		},
		"back_link": {
			"minLength": 1,
			"type": "string"
		},
		"back_name": {
			"minLength": 1,
			"type": "string"
		},
		"back_text": {
			"minLength": 1,
			"type": "string"
		},
		"base_threat": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"base_threat_fixed": {
			"type": "boolean"
		},
		"base_threat_per_group": {
			"type": "boolean"
		},
		"base_threat_star": {
			"type": "boolean"
		},
		"boost": {
			"minimum": 1,
			"type": "integer"
		},
		"boost_star": {
			"type": "boolean"
		},
		"code": {
			"pattern": "^[0-9]{5,6}[a-z]?$",
			"type": "string"
		},
		"cost": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"cost_per_hero": {
			"type": "boolean"
		},
		"creator": {
			"minLength": 1,
			"type": "string"
		},
		"deck_limit": {
			"minimum": 1,
			"type": "integer"
		},
		"deck_options": {
			"items": {
				"properties": {
					"faction": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"limit": {
						"minimum": 1,
						"type": "integer"
					},
					"multi_aspect": {
						"type": "boolean"
					},
					"name_limit": {
						"minimum": 1,
						"type": "integer"
					},
					"per_faction": {
						"type": "boolean"
					},
					"resource": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"trait": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"type": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"use_deck_limit": {
						"type": "boolean"
					}
				},
				"type": "object"
			},
			"minItems": 1,
			"type": "array"
		},
		"deck_requirements": {
			"items": {
				"properties": {
					"aspects": {
						"minimum": 1,
						"type": "integer"
					},
					"limit": {
						"minimum": 1,
						"type": "integer"
					}
				},
				"type": "object"
			},
			"minItems": 1,
			"type": "array"
		},
		"defense": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"defense_star": {
			"type": "boolean"
		},
		"double_sided": {
			"type": "boolean"
		},
		"duplicate_of": {
			"pattern": "^[0-9a-z]{5}[0-9a-z]?$",
			"type": "string"
		},
		"errata": {
			"minLength": 1,
			"type": "string"
		},
		"escalation_threat": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"escalation_threat_fixed": {
			"type": "boolean"
		},
		"escalation_threat_star": {
			"type": "boolean"
		},
		"expansions_needed": {
			"minLength": 1,
			"type": "string"
		},
		"faction2_code": {
			"minLength": 1,
			"type": "string"
		},
		"faction_code": {
			"minLength": 1,
			"type": "string"
		},
		"flavor": {
			"minLength": 0,
			"type": "string"
		},
		"hand_size": {
			"minimum": 1,
			"type": "integer"
		},
		"health": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"health_per_group": {
			"type": "boolean"
		},
		"health_per_hero": {
			"type": "boolean"
		},
		"health_star": {
			"type": "boolean"
		},
		"hidden": {
			"type": "boolean"
		},
		"illustrator": {
			"pattern": ".*",
			"type": "string"
		},
		"is_unique": {
			"oneOf": [
				{
					"type": "boolean"
				},
				{
					"type": "null"
				}
			]
		},
		"meta": {
			"type": "object"
		},
		"multiverse_of": {
			"pattern": "^[0-9]{5,6}[a-z]?$",
			"type": "string"
		},
		"name": {
			"minLength": 1,
			"type": "string"
		},
		"octgn_id": {
			"minLength": 1,
			"type": "string"
		},
		"pack_code": {
			"maxLength": 255,
			"minLength": 2,
			"type": "string"
		},
		"permanent": {
			"type": "boolean"
		},
		"position": {
			"minimum": 1,
			"type": "integer"
		},
		"quantity": {
			"minimum": 1,
			"type": "integer"
		},
		"recover": {
			"minimum": 0,
			"type": "integer"
		},
		"recover_star": {
			"type": "boolean"
		},
		"resource_energy": {
			"minimum": 0,
			"type": "integer"
		},
		"resource_mental": {
			"minimum": 0,
			"type": "integer"
		},
		"resource_physical": {
			"minimum": 0,
			"type": "integer"
		},
		"resource_wild": {
			"minimum": 0,
			"type": "integer"
		},
		"restrictions": {
			"minLength": 1,
			"type": "string"
		},
		"scheme": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"scheme_acceleration": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_amplify": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_crisis": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_hazard": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_star": {
			"type": "boolean"
		},
		"set_code": {
			"minLength": 1,
			"type": "string"
		},
		"set_position": {
			"minimum": 1,
			"type": "integer"
		},
		"stage": {
			"minLength": 1,
			"type": "string"
		},
		"subname": {
			"minLength": 1,
			"type": "string"
		},
		"text": {
			"minLength": 1,
			"type": "string"
		},
		"threat": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"threat_fixed": {
			"type": "boolean"
		},
		"threat_per_group": {
			"type": "boolean"
		},
		"threat_star": {
			"type": "boolean"
		},
		"thwart": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"thwart_cost": {
			"minimum": 0,
			"type": "integer"
		},
		"thwart_star": {
			"type": "boolean"
		},
		"traits": {
			"minLength": 0,
			"type": "string"
		},
		"type_code": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"code",
		"pack_code",
		"position",
		"quantity"
	],
	"type": "object"
}

=== niclasdumesnil/marvelsdb_fanmade_data/pack/vnm_encounter.json
[
	{
		"boost": 2,
		"code": "20023",
		"faction_code": "encounter",
		"name": "Struggle for Control",
		"octgn_id": "f269a59a-4bc6-476f-9c36-20586a3de340",
		"pack_code": "vnm",
		"position": 23,
		"quantity": 1,
		"set_code": "vnm",
		"set_position": 23,
		"text": "<b><i>Give to the Flash Thompson player.</i></b>\nYou may flip to your alter-ego form. Choose:\n• Exhaust Flash Thompson and take 2 damage → discard this obligation.\n• Put 1 set-aside copy of Enraged Symbiote into play engaged with the first player. If you cannot, this card gains surge. Discard this obligation.",
		"type_code": "obligation"
	},
	{
		"base_threat": 2,
		"boost": 3,
		"code": "20024",
		"faction_code": "encounter",
		"flavor": "<b>The Venom symbiote is distraught, bonding with everyone it touches and sending them into a destructive rage.</b>",
		"name": "Klyntar Frenzy",
		"octgn_id": "a0444c6e-31f1-4de9-91ff-25b2de655cf2",
		"pack_code": "vnm",
		"position": 24,
		"quantity": 1,
		"scheme_hazard": 1,
		"set_code": "vnm_nemesis",
		"set_position": 1,
		"text": "Threat cannot be removed from this scheme while a [[Symbiote]] enemy is in play.",
		"threat": 0,
		"type_code": "side_scheme"
	},
	{
		"attack": 2,
		"boost_star": true,
		"code": "20025",
		"faction_code": "encounter",
		"flavor": "\"You will kneel before the true Destroyer!\"",
		"health": 2,
		"illustrator": "Julian Lopez",
		"name": "Enraged Symbiote",
		"octgn_id": "cdc9410c-6315-4c1c-a92e-4069c71ed2d8",
		"pack_code": "vnm",
		"position": 25,
		"quantity": 4,
		"scheme": 1,
		"set_code": "vnm_nemesis",
		"set_position": 2,
		"text": "Guard. Patrol. <i>(While this minion is engaged with you, you cannot thwart the main scheme.)</i>\n<i>(Venom's nemesis minion.)</i>\n<hr />\n[star] <b>Boost</b>: Put Enraged Symbiote into play engaged with you.",
		"traits": "Symbiote.",
		"type_code": "minion"
	}
]

=== niclasdumesnil/marvelsdb_fanmade_data/pack/weapon_hex_by_merlin.json
[
    {
        "code": "60501b",
        "faction_code": "hero",
        "hand_size": 6,
        "health": 12,
        "hidden": true,
        "is_unique": true,
        "name": "Laura Kinney",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000001",
        "pack_code": "weapon_hex_by_merlin",
        "position": 1,
        "quantity": 1,
        "recover": 6,
        "set_code": "weapon_hex_by_merlin",
        "text": "<i>Hex Chaos</i> — <b>Setup</b>: Find and put into play Chaos Magic.\n<b>Action</b>: shuffle a [[spell ]]card from your discard pile into your deck. (Limit once per round.)",
        "traits": "Mutant. Mystic. Warp.",
        "type_code": "alter_ego"
    },
    {
        "attack": 1,
        "back_link": "60501b",
        "code": "60501a",
        "defense": 2,
        "faction_code": "hero",
        "hand_size": 5,
        "health": 12,
        "is_unique": true,
        "meta": {
            "colors": [
                "#010101",
                "#cf2413",
                "#dd882d",
                "#201b1c"
            ],
            "offset": "-35px -33px"
        },
        "name": "Weapon Hex",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000001",
        "pack_code": "weapon_hex_by_merlin",
        "position": 1,
        "quantity": 1,
        "set_code": "weapon_hex_by_merlin",
        "text": "<i>Living Weapon </i>—<i> </i> <b>Response</b>: After you play a [[spell ]]event, ready Weapon Hex and discard X cards from the top of the encounter deck, where X is equal to the printed cost of that event (Limit once per phase.)",
        "thwart": 2,
        "traits": "Mystic. Warp.",
        "type_code": "hero"
    },
    {
        "code": "60502",
        "deck_limit": 1,
        "faction_code": "hero",
        "is_unique": true,
        "name": "Chaos Magic",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000002",
        "pack_code": "weapon_hex_by_merlin",
        "permanent": true,
        "position": 2,
        "quantity": 1,
        "resource_physical": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 1,
        "text": "Permanent. Setup.\n<b>Hero Action</b>: Exhaust Chaos Magic → search your deck for a [[spell ]]card and add it to your hand. Then discard 3 cards from the top of the encounter deck.",
        "traits": "Skill.",
        "type_code": "upgrade"
    },
    {
        "attack": 1,
        "attack_cost": 1,
        "code": "60503",
        "cost": 2,
        "deck_limit": 1,
        "faction_code": "hero",
        "health": 2,
        "is_unique": true,
        "name": "Speed Weasel",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000003",
        "pack_code": "weapon_hex_by_merlin",
        "position": 3,
        "quantity": 1,
        "resource_wild": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 2,
        "subname": "gavrill kinney",
        "text": "<b>Hero Response</b>: After Speed Weasel activates, ready Speed Weasel and Weapon Hex (limit once per round).\n<i>“My name is Speed Weasel!!!”</i>",
        "thwart": 1,
        "thwart_cost": 1,
        "traits": "Warp.",
        "type_code": "ally"
    },
    {
        "code": "60504",
        "cost": 1,
        "deck_limit": 2,
        "faction_code": "hero",
        "name": "Special Target",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000004",
        "pack_code": "weapon_hex_by_merlin",
        "position": 4,
        "quantity": 2,
        "resource_mental": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 3,
        "text": "<b>Hero Action</b>: Deal X damage to an enemy, where X is equal to your ATK.\n<i>“An Hex marks the spot.”</i>",
        "traits": "Spell.",
        "type_code": "event"
    },
    {
        "code": "60506",
        "cost": 1,
        "deck_limit": 2,
        "faction_code": "hero",
        "name": "From Nothing",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000006",
        "pack_code": "weapon_hex_by_merlin",
        "position": 5,
        "quantity": 2,
        "resource_mental": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 5,
        "text": "<b>Hero Action</b>: Remove X threat from a scheme, where X is equal to your THW.\n<i>“You're nothing.”</i>",
        "traits": "Spell.",
        "type_code": "event"
    },
    {
        "code": "60508",
        "cost": 3,
        "deck_limit": 2,
        "faction_code": "hero",
        "name": "Death Ray",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000008",
        "pack_code": "weapon_hex_by_merlin",
        "position": 6,
        "quantity": 2,
        "resource_physical": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 7,
        "text": "<b>Hero Action</b>: Deal 7 damage to an enemy. If you discard 1 card from the top of the encounter deck, deal those damage among enemies in play.\n“Don't threaten my sister!”\n<i>\n</i>",
        "traits": "Spell.",
        "type_code": "event"
    },
    {
        "code": "60510",
        "cost": 1,
        "deck_limit": 1,
        "faction_code": "hero",
        "name": "Magic Protection",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000010",
        "pack_code": "weapon_hex_by_merlin",
        "position": 7,
        "quantity": 1,
        "resource_energy": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 9,
        "text": "<b>Hero Interrupt</b>: When a friendly character would take any amount of damage, prevent 5 of that damage.",
        "traits": "Spell.",
        "type_code": "event"
    },
    {
        "code": "60511",
        "cost": 1,
        "deck_limit": 2,
        "faction_code": "hero",
        "name": "Warp Reality",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000011",
        "pack_code": "weapon_hex_by_merlin",
        "position": 8,
        "quantity": 2,
        "resource_physical": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 10,
        "text": "<b>Hero Interrupt</b>: When an encounter card is revealed from the encounter deck, cancel all of its effects and discard it. Discard cards from the top of the encounter deck equal to the number of boost icons on that card.",
        "traits": "Spell.",
        "type_code": "event"
    },
    {
        "code": "60513",
        "cost": 1,
        "deck_limit": 2,
        "faction_code": "hero",
        "name": "Regenerative Longevity",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000013",
        "pack_code": "weapon_hex_by_merlin",
        "position": 9,
        "quantity": 2,
        "resource_physical": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 12,
        "text": "<b>Action</b>: Heal 4 damage from among your identity and Speed Weasel.",
        "traits": "Superpower.",
        "type_code": "event"
    },
    {
        "code": "60515",
        "cost": 1,
        "deck_limit": 1,
        "faction_code": "hero",
        "name": "Chaotic Energy",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000015",
        "pack_code": "weapon_hex_by_merlin",
        "position": 10,
        "quantity": 1,
        "resource_energy": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 14,
        "text": "<b>Resource</b>: Exhaust Chaotic Energy → generate a [wild] resource for a [[spell ]]event.",
        "traits": "Item.",
        "type_code": "upgrade"
    },
    {
        "code": "60516",
        "deck_limit": 1,
        "faction_code": "hero",
        "name": "Magical Healing",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000016",
        "pack_code": "weapon_hex_by_merlin",
        "position": 11,
        "quantity": 1,
        "resource_energy": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 15,
        "text": "<b>Interrupt</b>: When Weapon Hex would be defeated, set her hit point dial to 6 instead. Then, discard this card.",
        "traits": "Skill. Spell.",
        "type_code": "upgrade"
    },
    {
        "code": "60517",
        "cost": 2,
        "deck_limit": 1,
        "faction_code": "hero",
        "is_unique": true,
        "name": "Weapon Hex's Claws",
        "octgn_id": "a609960e-607c-5889-921f-5e725e000017",
        "pack_code": "weapon_hex_by_merlin",
        "position": 12,
        "quantity": 1,
        "resource_physical": 1,
        "set_code": "weapon_hex_by_merlin",
        "set_position": 16,
        "text": "Restricted.\nWeapon Hex gets +2 ATK and her basic attacks gain piercing.",
        "traits": "Weapon.",
        "type_code": "upgrade"
    }
]

=== niclasdumesnil/marvelsdb_fanmade_data/pack/Karnak_by_1-2-punchboard.json
[
	{
		"code": "204001b",
		"faction_code": "hero",
		"hand_size": 6,
		"health": 10,
		"hidden": true,
		"is_unique": true,
		"name": "Karnak Mander-Azur",
		"octgn_id": "7f9b9b69-72b7-477d-9891-b4856c040001",
		"pack_code": "Karnak_by_1-2-punchboard",
		"position": 1,
		"quantity": 1,
		"recover": 3,
		"set_code": "Karnak_by_1-2-punchboard",
		"text": "<i>Meditation</i> — <b>Response</b>: After Karnak recovers, search your deck and discard pile for an [[ATTACK]], [[THWART]], or [[DEFENSE]] event. Add that card to your hand. If you searched your deck, shuffle it. (Limit once per phase.)",
		"traits": "Inhuman.",
		"type_code": "alter_ego"
	},
	{
		"attack": 2,
		"back_link": "204001b",
		"code": "204001a",
		"defense": 1,
		"faction_code": "hero",
		"hand_size": 5,
		"health": 10,
		"is_unique": true,
		"meta": {
			"colors": [
				"#03a81d",
				"#585858",
				"#ffffff",
				"#fffffd"
			],
			"offset": "-38px -33px"
		},
		"name": "Karnak",
		"octgn_id": "7f9b9b69-72b7-477d-9891-b4856c040001",
		"pack_code": "Karnak_by_1-2-punchboard",
		"position": 1,
		"quantity": 1,
		"set_code": "Karnak_by_1-2-punchboard",
		"text": "<i>Flaw in All Things</i> — <b>Response</b>: After Karnak attacks or thwarts and defeats an enemy or side scheme without dealing excess damage or removing excess threat, deal 1 damage to an enemy and ready Karnak. (Limit twice per round.)",
		"thwart": 2,
		"traits": "Inhuman.",
		"type_code": "hero"
	},
	{
		"attack": 2,
		"attack_cost": 1,
		"code": "204002",
		"cost": 3,
		"deck_limit": 1,
		"faction_code": "hero",
		"health": 3,
		"is_unique": true,
		"name": "Gorgon Petragon",
		"octgn_id": "7f9b9b69-72b7-477d-9891-b4856c040002",
		"pack_code": "Karnak_by_1-2-punchboard",
		"position": 2,
		"quantity": 1,
		"resource_energy": 1,
		"set_code": "Karnak_by_1-2-punchboard",
		"set_position": 1,
		"text": "<b>Response</b>: After Gorgon Petragon attacks, deal 1 damage to each enemy.\n<i>“I have devoted my entire life to honing the warrior's craft. I have sacrificed everything fighting for my people's future!”</i>",
		"thwart": 1,
		"thwart_cost": 1,
		"traits": "Inhuman.",
		"type_code": "ally"
	},
	{
		"code": "204003",
		"cost": 0,
		"deck_limit": 4,
		"faction_code": "hero",
		"name": "Excess and Restraint",
		"octgn_id": "7f9b9b69-72b7-477d-9891-b4856c040003",
		"pack_code": "Karnak_by_1-2-punchboard",
		"position": 3,
		"quantity": 4,
		"resource_physical": 1,
		"set_code": "Karnak_by_1-2-punchboard",
		"set_position": 2,
		"text": "<b>Hero Interrupt</b>: When Karnak attacks, increase or decrease (you choose) the damage that attack deals by 1.\n<b>Hero Interrupt</b>: When Karnak thwarts, increase or decrease (you choose) the threat that thwart removes by 1.",
		"traits": "Attack. Skill. Thwart.",
		"type_code": "event"
	},
	{
		"code": "204004",
		"cost": 3,
		"deck_limit": 2,
		"faction_code": "hero",
		"name": "Disarm",
		"octgn_id": "7f9b9b69-72b7-477d-9891-b4856c040004",
		"pack_code": "Karnak_by_1-2-punchboard",
		"position": 4,
		"quantity": 2,
		"resource_mental": 1,
		"set_code": "Karnak_by_1-2-punchboard",
		"set_position": 6,
		"text": "<b>Hero Action</b> <i>(thwart)</i>: Remove 3 threat from a scheme and discard an [[ARMOR]], [[TECH]], or [[WEAPON]] attachment from an enemy. If no attachment was discarded this way, confuse the villain instead.\n<i>“In time, all we rely on will shatter and fall.”</i>",
		"traits": "Skill. Thwart.",
		"type_code": "event"
	},
	{
		"code": "204005",
		"cost": 2,
		"deck_limit": 2,
		"faction_code": "hero",
		"name": "Peerless Defense",
		"octgn_id": "7f9b9b69-72b7-477d-9891-b4856c040005",
		"pack_code": "Karnak_by_1-2-punchboard",
		"position": 5,
		"quantity": 2,
		"resource_mental": 1,
		"set_code": "Karnak_by_1-2-punchboard",
		"set_position": 8,
		"text": "<b>Hero Interrupt</b> <i>(thwart)</i>: When you would take any amount of damage, discard Peerless Defense → prevent up to 3 of that damage. Remove threat from a scheme equal to the amount of damage prevented this way.",
		"traits": "Preparation. Skill. Thwart.",
		"type_code": "upgrade"
	},
	{
		"code": "204006",
		"cost": 1,
		"deck_limit": 2,
		"faction_code": "hero",
		"name": "Probing for Weakness",
		"octgn_id": "7f9b9b69-72b7-477d-9891-b4856c040006",
		"pack_code": "Karnak_by_1-2-punchboard",
		"position": 6,
		"quantity": 2,
		"resource_energy": 1,
		"set_code": "Karnak_by_1-2-punchboard",
		"set_position": 10,
		"text": "<b>Hero Action</b> <i>(attack)</i>: Deal 1 damage to an enemy. This attack gains piercing. If this attack discarded a tough status card, deal another 3 damage to that enemy.\n<i>“Where is the flaw?”</i>",
		"traits": "Attack. Skill.",
		"type_code": "event"
	},
	{
		"code": "204007",
		"deck_limit": 2,
		"faction_code": "hero",
		"name": "Martial Training",
		"octgn_id": "7f9b9b69-72b7-477d-9891-b4856c040007",
		"pack_code": "Karnak_by_1-2-punchboard",
		"position": 7,
		"quantity": 2,
		"resource_wild": 1,
		"set_code": "Karnak_by_1-2-punchboard",
		"set_position": 12,
		"text": "If Karnak has attacked or thwarted this turn, double the number of resources this card generates.",
		"type_code": "resource"
	},
	{
		"code": "204008",
		"cost": 2,
		"deck_limit": 1,
		"faction_code": "hero",
		"name": "Tower of Wisdom",
		"octgn_id": "7f9b9b69-72b7-477d-9891-b4856c040008",
		"pack_code": "Karnak_by_1-2-punchboard",
		"position": 8,
		"quantity": 1,
		"resource_wild": 1,
		"set_code": "Karnak_by_1-2-punchboard",
		"set_position": 14,
		"text": "Karnak Mander-Azur gets +2 REC.\n<b>Alter-Ego Action</b>: Exhaust Tower of Wisdom → remove 1 threat from a scheme.",
		"traits": "Inhuman. Location.",
		"type_code": "support"
	},
	{
		"code": "204009",
		"cost": 4,
		"deck_limit": 1,
		"faction_code": "hero",
		"name": "The Shatterer",
		"octgn_id": "7f9b9b69-72b7-477d-9891-b4856c040009",
		"pack_code": "Karnak_by_1-2-punchboard",
		"position": 9,
		"quantity": 1,
		"resource_physical": 1,
		"set_code": "Karnak_by_1-2-punchboard",
		"set_position": 15,
		"text": "<b>Hero Action</b> <i>(attack)</i>: Deal between 1 and 6 damage to an enemy. If you defeat a minion engaged with a player, stun the villain and each minion engaged with that player.\n<i>“It is my discipline to be able to sense the weakest spot in any object -- And my power to shatter it.”</i>",
		"traits": "Attack. Skill.",
		"type_code": "event"
	}
]

=== niclasdumesnil/marvelsdb_fanmade_data/pack/luke_cage_by_rainy_encounter.json
[
    {
        "boost": 2,
        "code": "203612",
        "faction_code": "encounter",
        "name": "Relationship Breakdown",
        "octgn_id": "2ff1dcda-c503-479c-9a9e-22f9ba036012",
        "pack_code": "luke_cage_by_rainy",
        "position": 12,
        "quantity": 1,
        "set_code": "luke_cage_by_rainy",
        "text": "You may flip to alter-ego form.\nWhile this card is in play, flip your hero-specific ally and supports facedown.\n<b>Alter-Ego Action</b>: Exhaust Luke Cage → remove Relationship Breakdown from the game and flip face-up each card that was flipped facedown by this obligation.",
        "type_code": "obligation"
    },
    {
        "base_threat": 2,
        "boost": 2,
        "code": "203613",
        "faction_code": "encounter",
        "name": "A New Kingpin",
        "octgn_id": "2ff1dcda-c503-479c-9a9e-22f9ba036013",
        "pack_code": "luke_cage_by_rainy",
        "position": 13,
        "quantity": 1,
        "set_code": "luke_cage_by_rainy_nemesis",
        "set_position": 1,
        "text": "<i>Diamondback is flooding the street with a new drug that gives superpowers, aiming to become the new Kingpin of Crime by hooking up other criminals.\n</i><b>When Revealed</b>: Give the villain 1 facedown boost card and a tough status card.\n[acceleration]",
        "type_code": "side_scheme"
    },
    {
        "attack": 2,
        "attack_star": true,
        "boost": 2,
        "code": "203614",
        "faction_code": "encounter",
        "flavor": "If you fall in line behind me, I can hook you up.",
        "health": 5,
        "is_unique": true,
        "name": "Diamondback",
        "octgn_id": "2ff1dcda-c503-479c-9a9e-22f9ba036014",
        "pack_code": "luke_cage_by_rainy",
        "position": 14,
        "quantity": 1,
        "scheme": 2,
        "scheme_star": true,
        "set_code": "luke_cage_by_rainy_nemesis",
        "set_position": 2,
        "text": "Toughness.\n[star] <b>Forced Interrupt</b>: When Diamondback would activate, seek an attachment from the encounter deck and reveal it.\n<i>(Luke Cage's nemesis minion.)</i>",
        "traits": "Criminal.",
        "type_code": "minion"
    },
    {
        "boost": 3,
        "code": "203615",
        "faction_code": "encounter",
        "name": "Jacked-Up",
        "octgn_id": "2ff1dcda-c503-479c-9a9e-22f9ba036015",
        "pack_code": "luke_cage_by_rainy",
        "position": 15,
        "quantity": 1,
        "set_code": "luke_cage_by_rainy_nemesis",
        "set_position": 3,
        "text": "Attach to Diamondback, otherwise attach to the minion with the most remaining hit points and give them a tough status card. If you cannot attach this card, this card gains surge.\nAttached character gets +2 hit points.",
        "traits": "Condition. Superpower.",
        "type_code": "attachment"
    },
    {
        "boost": 1,
        "code": "203616",
        "faction_code": "encounter",
        "name": "Diamond",
        "octgn_id": "2ff1dcda-c503-479c-9a9e-22f9ba036016",
        "pack_code": "luke_cage_by_rainy",
        "position": 16,
        "quantity": 2,
        "set_code": "luke_cage_by_rainy_nemesis",
        "set_position": 4,
        "text": "Attach to the minion with the most remaining hit points without another copy of Diamond attached and give them a tough status card. If you cannot attach this card, this card gains surge.\n<i>Diamond produces a second-long surge of energy in its consumer, followed by an unstoppable rush that lasts for hours.</i>",
        "traits": "Drug.",
        "type_code": "attachment"
    }
]
