=== niclasdumesnil/marvelsdb_fanmade_data/schema/card_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"additionalProperties": true,
	"dependencies": {
		"name": [
			"faction_code",
			"type_code"
		]
	},
	"description": "JSON Schema for a Marvel Champions card — derived from Card.orm.yml",
	"properties": {
		"alt_art": {
			"type": "boolean"
		},
		"attack": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"attack_cost": {
			"minimum": 0,
			"type": "integer"
		},
		"attack_star": {
			"type": "boolean"
		},
		"back_flavor": {
			"minLength": 1,
			"type": "string"
		},
		"back_link": {
			"minLength": 1,
			"type": "string"
		},
		"back_name": {
			"minLength": 1,
			"type": "string"
		},
		"back_text": {
			"minLength": 1,
			"type": "string"
		},
		"base_threat": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"base_threat_fixed": {
			"type": "boolean"
		},
		"base_threat_per_group": {
			"type": "boolean"
		},
		"base_threat_star": {
			"type": "boolean"
		},
		"boost": {
			"minimum": 1,
			"type": "integer"
		},
		"boost_star": {
			"type": "boolean"
		},
		"code": {
			"pattern": "^[0-9]{5,6}[a-z]?$",
			"type": "string"
		},
		"cost": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"cost_per_hero": {
			"type": "boolean"
		},
		"creator": {
			"minLength": 1,
			"type": "string"
		},
		"deck_limit": {
			"minimum": 1,
			"type": "integer"
		},
		"deck_options": {
			"items": {
				"properties": {
					"faction": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"limit": {
						"minimum": 1,
						"type": "integer"
					},
					"multi_aspect": {
						"type": "boolean"
					},
					"name_limit": {
						"minimum": 1,
						"type": "integer"
					},
					"per_faction": {
						"type": "boolean"
					},
					"resource": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"trait": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"type": {
						"items": {
							"minLength": 1,
							"type": "string"
						},
						"minItems": 1,
						"type": "array"
					},
					"use_deck_limit": {
						"type": "boolean"
					}
				},
				"type": "object"
			},
			"minItems": 1,
			"type": "array"
		},
		"deck_requirements": {
			"items": {
				"properties": {
					"aspects": {
						"minimum": 1,
						"type": "integer"
					},
					"limit": {
						"minimum": 1,
						"type": "integer"
					}
				},
				"type": "object"
			},
			"minItems": 1,
			"type": "array"
		},
		"defense": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"defense_star": {
			"type": "boolean"
		},
		"double_sided": {
			"type": "boolean"
		},
		"duplicate_of": {
			"pattern": "^[0-9a-z]{5}[0-9a-z]?$",
			"type": "string"
		},
		"errata": {
			"minLength": 1,
			"type": "string"
		},
		"escalation_threat": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"escalation_threat_fixed": {
			"type": "boolean"
		},
		"escalation_threat_star": {
			"type": "boolean"
		},
		"expansions_needed": {
			"minLength": 1,
			"type": "string"
		},
		"faction2_code": {
			"minLength": 1,
			"type": "string"
		},
		"faction_code": {
			"minLength": 1,
			"type": "string"
		},
		"flavor": {
			"minLength": 0,
			"type": "string"
		},
		"hand_size": {
			"minimum": 1,
			"type": "integer"
		},
		"health": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"health_per_group": {
			"type": "boolean"
		},
		"health_per_hero": {
			"type": "boolean"
		},
		"health_star": {
			"type": "boolean"
		},
		"hidden": {
			"type": "boolean"
		},
		"illustrator": {
			"pattern": ".*",
			"type": "string"
		},
		"is_unique": {
			"oneOf": [
				{
					"type": "boolean"
				},
				{
					"type": "null"
				}
			]
		},
		"meta": {
			"type": "object"
		},
		"multiverse_of": {
			"pattern": "^[0-9]{5,6}[a-z]?$",
			"type": "string"
		},
		"name": {
			"minLength": 1,
			"type": "string"
		},
		"octgn_id": {
			"minLength": 1,
			"type": "string"
		},
		"pack_code": {
			"maxLength": 255,
			"minLength": 2,
			"type": "string"
		},
		"permanent": {
			"type": "boolean"
		},
		"position": {
			"minimum": 1,
			"type": "integer"
		},
		"quantity": {
			"minimum": 1,
			"type": "integer"
		},
		"recover": {
			"minimum": 0,
			"type": "integer"
		},
		"recover_star": {
			"type": "boolean"
		},
		"resource_energy": {
			"minimum": 0,
			"type": "integer"
		},
		"resource_mental": {
			"minimum": 0,
			"type": "integer"
		},
		"resource_physical": {
			"minimum": 0,
			"type": "integer"
		},
		"resource_wild": {
			"minimum": 0,
			"type": "integer"
		},
		"restrictions": {
			"minLength": 1,
			"type": "string"
		},
		"scheme": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"scheme_acceleration": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_amplify": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_crisis": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_hazard": {
			"minimum": 1,
			"type": "integer"
		},
		"scheme_star": {
			"type": "boolean"
		},
		"set_code": {
			"minLength": 1,
			"type": "string"
		},
		"set_position": {
			"minimum": 1,
			"type": "integer"
		},
		"stage": {
			"minLength": 1,
			"type": "string"
		},
		"subname": {
			"minLength": 1,
			"type": "string"
		},
		"text": {
			"minLength": 1,
			"type": "string"
		},
		"threat": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"threat_fixed": {
			"type": "boolean"
		},
		"threat_per_group": {
			"type": "boolean"
		},
		"threat_star": {
			"type": "boolean"
		},
		"thwart": {
			"oneOf": [
				{
					"minimum": -1,
					"type": "integer"
				},
				{
					"type": "null"
				}
			]
		},
		"thwart_cost": {
			"minimum": 0,
			"type": "integer"
		},
		"thwart_star": {
			"type": "boolean"
		},
		"traits": {
			"minLength": 0,
			"type": "string"
		},
		"type_code": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"code",
		"pack_code",
		"position",
		"quantity"
	],
	"type": "object"
}

=== niclasdumesnil/marvelsdb_fanmade_data/pack/firestar_by_bluehg.json
[
	{
		"code": "205801b",
		"faction_code": "hero",
		"flavor": "“I'm going to stand side by side with you to protect our right to live in this world.”",
		"hand_size": 6,
		"health": 10,
		"hidden": true,
		"is_unique": true,
		"name": "Angelica Jones",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058001",
		"pack_code": "firestar_by_bluehg",
		"position": 1,
		"quantity": 1,
		"recover": 3,
		"set_code": "firestar_by_bluehg",
		"text": "<i>Schooling for the Gifted</i> — <b>Action</b>: Put a card from your discard pile on top of your deck. (Limit once per round.)",
		"traits": "Mutant.",
		"type_code": "alter_ego"
	},
	{
		"attack": 2,
		"attack_star": true,
		"back_link": "205801b",
		"code": "205801a",
		"defense": 1,
		"defense_star": true,
		"faction_code": "hero",
		"hand_size": 5,
		"health": 10,
		"is_unique": true,
		"meta": {
			"colors": [
				"#e8c136",
				"#ffffff",
				"#e8c136",
				"#cc262a"
			]
		},
		"name": "Firestar",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058001",
		"pack_code": "firestar_by_bluehg",
		"position": 1,
		"quantity": 1,
		"set_code": "firestar_by_bluehg",
		"text": "[star] <i>Supercharge</i> — <b>Interrupt</b>: When you use a basic power, discard up to 4 cards from the top of your deck → if at least 1 [energy] or [wild] resource was discarded this way, you get +1 to that basic power for this use. (Limit once per phase.)",
		"thwart": 1,
		"thwart_star": true,
		"traits": "X-Men.",
		"type_code": "hero"
	},
	{
		"attack": 3,
		"attack_cost": 2,
		"attack_star": true,
		"code": "205802",
		"cost": 3,
		"deck_limit": 1,
		"faction_code": "hero",
		"flavor": "“I'm not giving up, Angelica.”",
		"health": 3,
		"is_unique": true,
		"name": "Justice",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058002",
		"pack_code": "firestar_by_bluehg",
		"position": 2,
		"quantity": 1,
		"resource_mental": 1,
		"set_code": "firestar_by_bluehg",
		"set_position": 1,
		"text": "[star] <b>Response</b>: After Justice uses a basic power, put an identity-specific card from your discard pile on top of your deck.",
		"thwart": 1,
		"thwart_cost": 1,
		"thwart_star": true,
		"traits": "Avenger.",
		"type_code": "ally"
	},
	{
		"code": "205803",
		"cost": 3,
		"deck_limit": 3,
		"faction_code": "hero",
		"name": "Microwave Blast",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058003",
		"pack_code": "firestar_by_bluehg",
		"position": 3,
		"quantity": 3,
		"resource_physical": 1,
		"set_code": "firestar_by_bluehg",
		"set_position": 2,
		"text": "<b>Hero Action</b> <i>(attack)</i>: Deal 5 damage to an enemy. Discard up to 4 cards from the top of your deck. For each [energy] or [wild] resource discarded as a part of this effect, this attack deals 1 additional damage. If 3 or more [energy] or [wild] icons were discarded, deal 1 damage to each minion engaged with you.",
		"traits": "Attack. Superpower.",
		"type_code": "event"
	},
	{
		"code": "205804",
		"cost": 2,
		"deck_limit": 2,
		"faction_code": "hero",
		"flavor": "“I got this.”",
		"name": "Radiative Vision",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058004",
		"pack_code": "firestar_by_bluehg",
		"position": 4,
		"quantity": 2,
		"resource_mental": 1,
		"set_code": "firestar_by_bluehg",
		"set_position": 5,
		"text": "<b>Hero Action</b> <i>(thwart)</i>: Remove 3 threat from a scheme. Discard up to 4 cards from the top of your deck. For each [energy] or [wild] resource discarded this way, remove 1 threat from a scheme.",
		"traits": "Superpower. Thwart.",
		"type_code": "event"
	},
	{
		"code": "205805",
		"deck_limit": 3,
		"faction_code": "hero",
		"name": "Ambient Microwaves",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058005",
		"pack_code": "firestar_by_bluehg",
		"position": 5,
		"quantity": 3,
		"resource_energy": 2,
		"set_code": "firestar_by_bluehg",
		"set_position": 7,
		"text": "<b>Interrupt</b>: When you spend this card, shuffle it into your deck instead of discarding it.\n<b>Hero Response</b>: After this card is discarded from the top of your deck, ready Firestar.",
		"type_code": "resource"
	},
	{
		"code": "205806",
		"cost": 1,
		"deck_limit": 2,
		"faction_code": "hero",
		"name": "Clandestine Operative",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058006",
		"pack_code": "firestar_by_bluehg",
		"position": 6,
		"quantity": 2,
		"resource_energy": 1,
		"set_code": "firestar_by_bluehg",
		"set_position": 10,
		"text": "Max 1 per player.\nFirestar gets +1 THW.\n<b>Forced Response</b>: After Firestar attacks, discard up to 4 cards from the top of your deck. For each [energy] or [wild] resource discarded this way, deal 1 damage to an enemy or remove 1 threat from a scheme. Discard Clandestine Operative.",
		"traits": "Tactic.",
		"type_code": "upgrade"
	},
	{
		"code": "205807",
		"cost": 1,
		"deck_limit": 1,
		"faction_code": "hero",
		"name": "Once an Avenger...",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058007",
		"pack_code": "firestar_by_bluehg",
		"position": 7,
		"quantity": 1,
		"resource_energy": 1,
		"set_code": "firestar_by_bluehg",
		"set_position": 12,
		"text": "Firestar gains the [[AVENGER]] trait.\n<b>Hero Interrupt</b>: After you defeat an enemy or a scheme, exhaust Once an Avenger... → put a resource card from your discard pile on top of your deck.",
		"traits": "Title.",
		"type_code": "upgrade"
	},
	{
		"code": "205808",
		"cost": 2,
		"deck_limit": 1,
		"faction_code": "hero",
		"name": "Plasma Propulsion",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058008",
		"pack_code": "firestar_by_bluehg",
		"position": 8,
		"quantity": 1,
		"resource_physical": 1,
		"set_code": "firestar_by_bluehg",
		"set_position": 13,
		"text": "Firestar gets +1 DEF and gains retaliate 1 and the [[AERIAL]] trait.\n<b>Hero Interrupt</b>: When you would discard cards from the top of your deck, exhaust Plasma Propulsion → you may discard up to 2 additional cards from the top of your deck.",
		"traits": "Superpower.",
		"type_code": "upgrade"
	},
	{
		"code": "205809",
		"cost": 2,
		"deck_limit": 1,
		"faction_code": "hero",
		"name": "Solar Surge",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058009",
		"pack_code": "firestar_by_bluehg",
		"position": 9,
		"quantity": 1,
		"resource_mental": 1,
		"set_code": "firestar_by_bluehg",
		"set_position": 14,
		"text": "<b>Hero Interrupt</b>: When you use Firestar's \"Supercharge\" ability, if you discard at least 1 [energy] and/or [wild] resource, you get an additional +1 to the chosen basic power for this use.",
		"traits": "Superpower.",
		"type_code": "upgrade"
	},
	{
		"code": "205810",
		"cost": 3,
		"deck_limit": 1,
		"faction_code": "hero",
		"name": "Stellar Aura",
		"octgn_id": "616b40dd-052c-455d-a2bd-fc8b47058010",
		"pack_code": "firestar_by_bluehg",
		"position": 10,
		"quantity": 1,
		"resource_mental": 1,
		"set_code": "firestar_by_bluehg",
		"set_position": 15,
		"text": "<b>Hero Resource</b>: Exhaust Stellar Aura → generate the resources of the top resource card in your discard pile. Then, put that resource card on the bottom of your deck.",
		"traits": "Superpower.",
		"type_code": "upgrade"
	}
]

=== niclasdumesnil/marvelsdb_fanmade_data/pack/synthezoid.json
[
	{
		"code": "57032",
		"cost": 1,
		"faction_code": "basic",
		"name": "You're Out of Order!",
		"octgn_id": "2b778323-b4d9-4567-999d-42e7de057032",
		"pack_code": "synthezoid",
		"position": 32,
		"quantity": 1,
		"resource_wild": 1,
		"set_code": "she_hulk_leader",
		"text": "<b>Interrupt</b>: When any amount of threat would be placed on the main scheme, say \"I object!\" and prevent 3 of that threat.",
		"type_code": "event"
	},
	{
		"code": "57033",
		"cost": 2,
		"faction_code": "basic",
		"flavor": "\"That does it! Now I'm mad!\" —She-Hulk",
		"name": "She-Hulk Smash",
		"octgn_id": "2b778323-b4d9-4567-999d-42e7de057033",
		"pack_code": "synthezoid",
		"position": 33,
		"quantity": 1,
		"resource_wild": 1,
		"set_code": "she_hulk_leader",
		"text": "<b>Action</b>: Your She-Hulk leader attacks the enemy leader. If you spent a [physical] resource to pay for this event, stun the enemy leader.",
		"type_code": "event"
	},
	{
		"code": "57034",
		"cost": 1,
		"faction_code": "basic",
		"name": "Make Me Angry",
		"octgn_id": "2b778323-b4d9-4567-999d-42e7de057034",
		"pack_code": "synthezoid",
		"position": 34,
		"quantity": 1,
		"resource_physical": 1,
		"set_code": "she_hulk_leader",
		"text": "Attach to your She-Hulk leader.\n<b>Forced Response</b>: After a hero or leader attacks attached She-Hulk, she attacks that character. Then, discard this card.",
		"type_code": "upgrade"
	},
	{
		"code": "57035",
		"faction_code": "basic",
		"name": "Legal Counsel",
		"octgn_id": "2b778323-b4d9-4567-999d-42e7de057035",
		"pack_code": "synthezoid",
		"position": 35,
		"quantity": 1,
		"resource_wild": 2,
		"set_code": "she_hulk_leader",
		"text": "<b>Hero Response</b>: After you spend this resource, move 1 threat from the main scheme to your leader's main scheme.",
		"type_code": "resource"
	},
	{
		"code": "57074",
		"cost": 2,
		"faction_code": "basic",
		"flavor": "\"There is no victory without risk.\" —Vision",
		"name": "Calculated Risk",
		"octgn_id": "2b778323-b4d9-4567-999d-42e7de057074",
		"pack_code": "synthezoid",
		"position": 74,
		"quantity": 1,
		"resource_wild": 1,
		"set_code": "vision_leader",
		"text": "<b>Action</b>: Search the top 5 cards of your leader's encounter deck for an encounter card and deal it to the first player on the enemy team as a facedown encounter card.",
		"type_code": "event"
	},
	{
		"code": "57075",
		"cost": 2,
		"faction_code": "basic",
		"name": "Synthezoid Strike",
		"octgn_id": "2b778323-b4d9-4567-999d-42e7de057075",
		"pack_code": "synthezoid",
		"position": 75,
		"quantity": 1,
		"resource_wild": 1,
		"set_code": "vision_leader",
		"text": "<b>Action</b>: Your Vision leader attacks the enemy leader. If Vision's mass form attachment is:\n• Dense, Vision gets +1 ATK for this attack and this attack gains piercing.\n• Intangible, flip it to Dense before resolving this attack.",
		"type_code": "event"
	},
	{
		"code": "57076",
		"cost": 0,
		"faction_code": "basic",
		"flavor": "\"My ability to phase through electronics can disrupt Stark's technology.\" —Vision",
		"name": "Phased Out",
		"octgn_id": "2b778323-b4d9-4567-999d-42e7de057076",
		"pack_code": "synthezoid",
		"position": 76,
		"quantity": 1,
		"resource_wild": 1,
		"set_code": "vision_leader",
		"text": "<b>Action</b>: Choose an attachment on the enemy leader with the text <b>\"Hero Response\"</b> or <b>\"Hero Interrupt\"</b> and discard it.",
		"type_code": "event"
	},
	{
		"code": "57077",
		"faction_code": "basic",
		"name": "Android Assistance",
		"octgn_id": "2b778323-b4d9-4567-999d-42e7de057077",
		"pack_code": "synthezoid",
		"position": 77,
		"quantity": 1,
		"resource_wild": 2,
		"set_code": "vision_leader",
		"text": "<b>Hero Interrupt</b>: When you spend this resource, flip your Vision leader's mass form attachment.",
		"type_code": "resource"
	}
]

=== niclasdumesnil/marvelsdb_fanmade_data/pack/red_guardian_by_kajislav.json
[
	{
		"attack": 2,
		"back_link": "202601b",
		"code": "202601a",
		"defense": 2,
		"faction_code": "hero",
		"hand_size": 5,
		"health": 11,
		"is_unique": true,
		"meta": {
			"colors": [
				"#121819",
				"#d01d15",
				"#c8d0cf",
				"#000000"
			],
			"offset": "-35px -33px"
		},
		"name": "Red Guardian",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026001",
		"pack_code": "red_guardian_by_kajislav",
		"position": 1,
		"quantity": 1,
		"set_code": "red_guardian_by_kajislav",
		"text": "<i>Shield Launch </i>— <b>Action </b><i>(attack/thwart)</i>: Attach Red Guardian's Shield from your hand to an enemy or a scheme → deal 2 damage to that enemy or remove 2 threat from that scheme.<i>\n\"I had no expectations. Only dreams.\"</i>",
		"thwart": 2,
		"traits": "Soldier. Thunderbolt.",
		"type_code": "hero"
	},
	{
		"code": "202601b",
		"faction_code": "hero",
		"hand_size": 6,
		"health": 11,
		"hidden": true,
		"is_unique": true,
		"name": "Alexei Shostakov",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026001",
		"pack_code": "red_guardian_by_kajislav",
		"position": 1,
		"quantity": 1,
		"recover": 3,
		"set_code": "red_guardian_by_kajislav",
		"text": "<i>Rescue the Shield</i> — <b>Action</b>: Spend 1 resource of any type → search your deck and discard pile for Red Guardian's Shield and add it to your hand. (Limit once per round).\n<i>\"There's no place like home.\"</i>",
		"traits": "Soldier.",
		"type_code": "alter_ego"
	},
	{
		"attack": 2,
		"attack_cost": 1,
		"attack_star": true,
		"code": "202603",
		"cost": 3,
		"deck_limit": 1,
		"faction_code": "hero",
		"health": 3,
		"is_unique": true,
		"name": "White Widow",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026003",
		"pack_code": "red_guardian_by_kajislav",
		"position": 3,
		"quantity": 1,
		"resource_wild": 1,
		"set_code": "red_guardian_by_kajislav",
		"set_position": 2,
		"subname": "Yelena Belova",
		"text": "[star] <b>Response</b>: After White Widow attacks an enemy with Red Guardian's Shield attached, confuse an enemy.\n<i>\"I tried to assassinate you. Assassinations only happen to important people. It's a compliment.\"</i>",
		"thwart": 2,
		"thwart_cost": 1,
		"traits": "Spy. Thunderbolt.",
		"type_code": "ally"
	},
	{
		"attack": 2,
		"attack_cost": 1,
		"attack_star": true,
		"code": "202602",
		"cost": 3,
		"deck_limit": 1,
		"faction_code": "hero",
		"health": 3,
		"is_unique": true,
		"name": "Black Widow",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026002",
		"pack_code": "red_guardian_by_kajislav",
		"position": 2,
		"quantity": 1,
		"resource_wild": 1,
		"set_code": "red_guardian_by_kajislav",
		"set_position": 1,
		"subname": "Natasha Romanoff",
		"text": "[star] <b>Response</b>: After Black Widow attacks an enemy with Red Guardian's Shield attached, stun an enemy.\n<i>\"I don't need a weapon. I am a weapon.\"</i>",
		"thwart": 2,
		"thwart_cost": 1,
		"traits": "Spy. Thunderbolt.",
		"type_code": "ally"
	},
	{
		"code": "202604",
		"cost": 0,
		"deck_limit": 2,
		"faction_code": "hero",
		"name": "Shield Block",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026004",
		"pack_code": "red_guardian_by_kajislav",
		"position": 4,
		"quantity": 2,
		"resource_mental": 1,
		"set_code": "red_guardian_by_kajislav",
		"set_position": 3,
		"text": "Play only if Red Guardian's Shield is in your hand.\n<b>Interrupt</b><i> (defense)</i>: When you would take any amount of damage, prevent all of that damage.[[\n]]<i>\"I've come too far to give up now.\" —Red Guardian</i>",
		"traits": "Defense.",
		"type_code": "event"
	},
	{
		"code": "202606",
		"cost": 2,
		"deck_limit": 2,
		"faction_code": "hero",
		"name": "Shielded Drop",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026006",
		"pack_code": "red_guardian_by_kajislav",
		"position": 6,
		"quantity": 2,
		"resource_mental": 1,
		"set_code": "red_guardian_by_kajislav",
		"set_position": 5,
		"text": "Play only if Red Guardian's Shield is in your hand.\n<b>Hero Action</b><i> (thwart)</i>: Remove 5 threat from a scheme.[[\n]]<i>\"If there is backup here, it is all of you! This operation is mine.\" —Red Guardian</i>",
		"traits": "Aerial. Thwart.",
		"type_code": "event"
	},
	{
		"code": "202608",
		"cost": -1,
		"deck_limit": 3,
		"faction_code": "hero",
		"name": "Shield Ricochet",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026008",
		"pack_code": "red_guardian_by_kajislav",
		"position": 8,
		"quantity": 3,
		"resource_energy": 1,
		"set_code": "red_guardian_by_kajislav",
		"set_position": 7,
		"text": "Play only if Red Guardian's Shield is attached to an enemy or a scheme.\n<b>Hero Action</b>: Move Red Guardian's Shield to an enemy or a scheme X times → deal 3 damage to each enemy and remove 3 threat from each scheme Red Guardian's Shield was moved to.[[\n]]<i>“Aren't you all regretting that you neglected to practice speed reloading?” —Albert</i>",
		"traits": "Tactic.",
		"type_code": "event"
	},
	{
		"code": "202611",
		"cost": 2,
		"deck_limit": 2,
		"faction_code": "hero",
		"name": "Shield Strike",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026011",
		"pack_code": "red_guardian_by_kajislav",
		"position": 11,
		"quantity": 2,
		"resource_physical": 1,
		"set_code": "red_guardian_by_kajislav",
		"set_position": 10,
		"text": "Play only if Red Guardian's Shield is in your hand.\n<b>Hero Action</b><i> (attack)</i>: Deal 5 damage to an enemy. This attack gains piercing.[[\n]]<i>\"Don't kill anything until you know who is hunting who. And why.\" —Red Guardian</i>",
		"traits": "Attack.",
		"type_code": "event"
	},
	{
		"code": "202613",
		"cost": null,
		"deck_limit": 1,
		"faction_code": "hero",
		"is_unique": true,
		"name": "Red Guardian's Shield",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026013",
		"pack_code": "red_guardian_by_kajislav",
		"position": 13,
		"quantity": 1,
		"resource_physical": 1,
		"set_code": "red_guardian_by_kajislav",
		"set_position": 12,
		"text": "Temporary.\nWhile this card is in your hand, you can control 1 fewer restricted card.\n<b>Hero Interrupt</b>: When your turn ends, return this card from play to your hand.",
		"traits": "Weapon.",
		"type_code": "upgrade"
	},
	{
		"code": "202614",
		"cost": 2,
		"deck_limit": 1,
		"faction_code": "hero",
		"name": "Shield Arts",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026014",
		"pack_code": "red_guardian_by_kajislav",
		"position": 14,
		"quantity": 1,
		"resource_energy": 1,
		"set_code": "red_guardian_by_kajislav",
		"set_position": 13,
		"text": "<b>Hero Interrupt</b>: When Red Guardian uses a basic power against an enemy or a scheme with Red Guardian's Shield attached, exhaust Shield Arts → choose to either return Red Guardian's Shield to your hand or ready Red Guardian.",
		"traits": "Skill.",
		"type_code": "upgrade"
	},
	{
		"code": "202615",
		"cost": 2,
		"deck_limit": 1,
		"faction_code": "hero",
		"name": "Shield Harness",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026015",
		"pack_code": "red_guardian_by_kajislav",
		"position": 15,
		"quantity": 1,
		"resource_physical": 1,
		"set_code": "red_guardian_by_kajislav",
		"set_position": 14,
		"text": "Red Guardian's Shield does not count toward your hand size.\n<b>Hero Response</b>: After Red Guardian's Shield is discarded from play, exhaust Shield Harness → return Red Guardian's Shield to your hand.<i></i>",
		"traits": "Item.",
		"type_code": "upgrade"
	},
	{
		"code": "202616",
		"cost": 3,
		"deck_limit": 1,
		"faction_code": "hero",
		"name": "Soviet Super-Soldier",
		"octgn_id": "7bdcef20-83cc-47aa-a505-c601f5026016",
		"pack_code": "red_guardian_by_kajislav",
		"position": 16,
		"quantity": 1,
		"resource_physical": 1,
		"set_code": "red_guardian_by_kajislav",
		"set_position": 15,
		"text": "Red Guardian gains steady.<b>\nResource</b>: Exhaust Soviet Super- Soldier → generate a [wild] resource.<i>\n\"Today, I save a village, but soon... I save a dream!\" —Red Guardian</i>",
		"traits": "Title.",
		"type_code": "upgrade"
	}
]

=== niclasdumesnil/marvelsdb_fanmade_data/pack/civil_war_spoiler.json
[
    {
		"code": "55013",
		"cost": 3,
		"deck_limit": 3,
		"faction_code": "aggression",
		"name": "Aggressive Conditioning",
		"pack_code": "civil_war_spoiler",
		"position": 13,
		"quantity": 3,
		"resource_physical": 1,
		"traits": "Condition.",
		"type_code": "upgrade"
	},
    {
		"code": "55017",
		"cost": 3,
		"deck_limit": 3,
		"faction_code": "aggression",
		"name": "Savage Strike",
		"pack_code": "civil_war_spoiler",
		"position": 17,
		"quantity": 3,
		"resource_physical": 1,
		"traits": "Skill.",
		"type_code": "event"
	},
    {
		"code": "55016",
		"cost": 2,
		"deck_limit": 3,
		"faction_code": "aggression",
		"name": "Coup de Gr√¢ce",
		"pack_code": "civil_war_spoiler",
		"position": 16,
		"quantity": 3,
		"resource_mental": 1,
		"traits": "Attack.",
		"type_code": "event"
	},
    {
		"attack": 2,
		"attack_cost": 1,
		"attack_star": true,
		"code": "55010",
		"cost": 3,
		"deck_limit": 1,
		"faction_code": "aggression",
		"health": 3,
		"is_unique": true,
		"name": "Two-Gun Kid",	
		"pack_code": "civil_war_spoiler",
		"position": 10,
		"quantity": 1,
		"resource_mental": 1,
		"subname": "Matthew Hawk",
		"thwart": 1,
		"thwart_cost": 1,
		"traits": "Avenger.",
		"type_code": "ally"
	}

]

=== niclasdumesnil/marvelsdb_fanmade_data/pack/wonder_man_encounter.json
[
	{
		"boost": 2,
		"code": "58025",
		"faction_code": "encounter",
		"name": "Pacifism",
		"octgn_id": "7eb46497-8915-4be9-b31d-7bee67058025",
		"pack_code": "wonder_man",
		"position": 25,
		"quantity": 1,
		"set_code": "wonder_man",
		"text": "<b><i>Give to the Simon Williams player.</i></b>\nWonder Man cannot attack.\n<b>Alter-Ego Action</b>: Exhaust Simon Williams or discard 3 cards tucked under Ionic Physiology → discard this card.",
		"type_code": "obligation"
	},
	{
		"attack": 2,
		"attack_star": true,
		"boost": 2,
		"code": "58026",
		"faction_code": "encounter",
		"health": 3,
		"is_unique": true,
		"name": "Grim Reaper",
		"octgn_id": "7eb46497-8915-4be9-b31d-7bee67058026",
		"pack_code": "wonder_man",
		"position": 26,
		"quantity": 1,
		"scheme": 2,
		"set_code": "wonder_man_nemesis",
		"set_position": 1,
		"text": "Quickstrike.\n[star] <b>Forced Response</b>: After Grim Reaper attacks and defeats an ally, deal that ally's controller a facedown encounter card.",
		"traits": "Cyborg.",
		"type_code": "minion"
	},
	{
		"base_threat": 2,
		"boost": 3,
		"code": "58027",
		"faction_code": "encounter",
		"flavor": "\"If only you were my real brother...instead of this monstrosity you've become.\" —Grim Reaper",
		"name": "Brother vs. Brother",
		"octgn_id": "7eb46497-8915-4be9-b31d-7bee67058027",
		"pack_code": "wonder_man",
		"position": 27,
		"quantity": 1,
		"scheme_amplify": 1,
		"set_code": "wonder_man_nemesis",
		"set_position": 2,
		"text": "As an additional cost to attack Grim Reaper, you must discard 1 card from your hand.",
		"type_code": "side_scheme"
	},
	{
		"boost": 2,
		"code": "58028",
		"faction_code": "encounter",
		"flavor": "\"Nothing will get in my way!\" —Grim Reaper",
		"name": "Scythe Strike",
		"octgn_id": "7eb46497-8915-4be9-b31d-7bee67058028",
		"pack_code": "wonder_man",
		"position": 28,
		"quantity": 1,
		"set_code": "wonder_man_nemesis",
		"set_position": 3,
		"text": "<b>When Revealed</b>: If Grim Reaper is in play, he activates against you. Otherwise, take 2 indirect damage.",
		"type_code": "treachery"
	},
	{
		"boost_star": true,
		"code": "58029",
		"faction_code": "encounter",
		"name": "Death Cannot Die",
		"octgn_id": "7eb46497-8915-4be9-b31d-7bee67058029",
		"pack_code": "wonder_man",
		"position": 29,
		"quantity": 2,
		"set_code": "wonder_man_nemesis",
		"set_position": 4,
		"text": "<b>When Revealed</b>: Grim Reaper activates against you. If Grim Reaper is not in play, find him and reveal him.\n<hr />\n[star] <b>Boost</b>: If Grim Reaper is in play, he activates against you <i>(after this activation)</i>.",
		"type_code": "treachery"
	}
]
