=== niclasdumesnil/marvelsdb_fanmade_data/schema/faction_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"additionalProperties": true,
	"description": "JSON Schema for a Marvel Champions faction — derived from Faction.orm.yml",
	"properties": {
		"code": {
			"minLength": 1,
			"type": "string"
		},
		"is_primary": {
			"type": "boolean"
		},
		"name": {
			"minLength": 1,
			"type": "string"
		},
		"octgn_id": {
			"oneOf": [
				{
					"minLength": 1,
					"type": "string"
				},
				{
					"type": "null"
				}
			]
		}
	},
	"required": [
		"code",
		"name"
	],
	"type": "object"
}

=== niclasdumesnil/marvelsdb_fanmade_data/factions.json
[
    {
        "code": "aggression",
        "is_primary": true,
        "name": "Aggression",
        "octgn_id": null
    },
    {
        "code": "justice",
        "is_primary": true,
        "name": "Justice",
        "octgn_id": null
    },
    {
        "code": "encounter",
        "is_primary": false,
        "name": "Encounter",
        "octgn_id": null
    },
    {
        "code": "hero",
        "is_primary": false,
        "name": "Hero",
        "octgn_id": null
    },
    {
        "code": "basic",
        "is_primary": true,
        "name": "Basic",
        "octgn_id": null
    },
    {
        "code": "leadership",
        "is_primary": true,
        "name": "Leadership",
        "octgn_id": null
    },
    {
        "code": "protection",
        "is_primary": true,
        "name": "Protection",
        "octgn_id": null
    },
    {
        "code": "campaign",
        "is_primary": false,
        "name": "Campaign",
        "octgn_id": null
    },
    {
        "code": "pool",
        "is_primary": true,
        "name": "'Pool",
        "octgn_id": null
    }
]
